### ISSUE TITLE
addon-vnctoken don't work well with opennebula 6.02 - VNC does not open

### ISSUE THREAD

**Issue by chicco64** [storpool/addon-vnctoken#2]
Hi,
i installed opennebula-mini v.6.0.2 with bash script on debian10;
I would also like to activate the https functionality through proxy-nginx;
I have a wildcard ssl certificate for my domain, and it works perfectly on other nginx-proxies.
The functionality of opennebula would appear to be respected except the error message below "fireedge public endpoint is not working" and the vnc panel not opening.
I am attaching screenshots
can you help me ?
Thank you
<img width="622" alt="error-proxy" src="https://user-images.githubusercontent.com/59960414/133981978-51a66444-6ed1-4666-94b3-3a6fb74cca66.PNG">

**Comment by atodorov-storpool** [comment]
Hi,
I do not know wha opennebula-mini is. Also addon-vnctoken is an XML-RPC API extension to provide the needed auth tokens.

Please ask in the OpenNebula community forum how to resolve your issue.
